## NUMPY

In [16]:
import numpy as np # type: ignore
print(np.__version__)

2.0.1


In [20]:
a=np.array([1,2,3])
print(a)
print(a.shape)  
print(a.size)
print(a.ndim)
print(a.itemsize)
print(a.dtype)
print(a.astype(float))

[1 2 3]
(3,)
3
1
8
int64
[1. 2. 3.]


In [6]:
print(a[0])
a[0]=10   #To update the value of a specific index
print(a) 

1
[10  2  3]


# Python Lists vs Array


In [25]:
# Pyrhon Lists vs Array
l=[1,2,3,4]
l1=[5,6,7,8,9]
a=np.array([1,2,3,4,5])
a1=np.array([5,6,7,8,9])
l.append(5)  #Here the item will be append
#   #Here the item will not append because array didnt provide such operations
print(l)
# print(a)

[1, 2, 3, 4, 5]


In [26]:
l=l+[6]  # in list the 5 is added at the end of a list
a=a+np.array([2])  # but here in array the number 2 is added to every item in array
print(a)
print(l)

[3 4 5 6 7]
[1, 2, 3, 4, 5, 6]


In [27]:
l=l*2  # in list every item doubles by making square
a=a*2  # in array it will take square of each number
print(l,a)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6] [ 6  8 10 12 14]


# Dot Product of Python lists vs Array


In [30]:
# For Lists
dot=0
for i in range(len(l)):
    dot += l[i] * l1[i]
print(dot)    

# For array
dot=np.dot(a,a1)
print(dot)

# Another way 
dot=a*a1
sum1=np.sum(dot) #or sum1=(a*a1).sum()  or sum1=a @ a1
print(sum1)


115
115
115


# Speed Test b/w Numpy lists vs Array

In [2]:
import numpy as np
from numpy import random
from timeit import default_timer as timer

a=np.random.randn(1000)
b=np.random.randn(1000)
A=list(a)
B=list(b)
T=1000

def dot1():
    dot=0
    for i in range(len(A)):
        dot +=A[i]*B[i]
    return dot 

def dot2():
    return np.dot(a,b)

start=timer()
for t in range(T):
    dot1()
end=timer()
t1=end-start    

start=timer()
for t in range(T):
    dot2()
end=timer()
t2=end-start       

print(f"List calculations",t1)
print(f"np.dot",t2)
print(f"Average",t1/t2)   # Numpy Array is faster then python lists

List calculations 0.14533579999988433
np.dot 0.024553400002332637
Average 5.919172089652637


# 2D Array 

In [ ]:
a=np.array([[1,2,3],[2,3,4]])
print(a.shape)
print(a[1][1]) #or print(a[1,1])
#slicing
print(a[:,0])
print(a[0,:])
print(a.T)

# Indexing/Slicing/Boolean Indexing

In [ ]:
a=np.array([[1,2],[5,6]])
print(a)

b=a[0,1]
b=a[0,1:3]
b=a[:,0]
b=a[:,1]
b=a[-1,:]
b=a[-1,:-1]
print(b)


c=np.array([[1,2],[3,4],[5,6]])
bool_index= c > 2
print(bool_index)
print(a[a>2])

e=np.where(a>2,a,-1)
print(e)

f=np.array([10,13,15,8,91])
g=[1,2,3]
print(f[g])

even=np.argwhere(a%2==0).flatten()
print(a[even])

# Reshaping

In [52]:
import numpy as np
a=np.arange(1,7)
b=a.reshape(2,3)
c=a[np.newaxis,:]
print(c)
print(b)

[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]


# Concatenation

In [72]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.concatenate((a,b.T),axis=1)
d=np.hstack((a,b))
f=np.vstack((a,b))
print(f)
print(d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


# Broadcasting

In [79]:
x=np.array([[1,2,3],[4,5,6],[1,2,3],[4,5,6]])
y=np.array([[1,0,1],[1,0,1],[1,0,1],[1,0,1]]) 
z=x+y
print(z)

[[2 2 4]
 [5 5 7]
 [2 2 4]
 [5 5 7]]


# Function and Axes

In [87]:
a=np.array([[1,2,3,4,5,6],[4,5,6,7,8,9]])
print(a.sum())
print(a.sum(axis=1)) #axis=0 means row and 1 = coloumn
print(a.mean(axis=1))
print(a.var(axis=1))
print(np.std(a,axis=1))
print(np.size(a))
print(np.cumsum(a))
print(np.cumprod(a))

60
[21 39]
[3.5 6.5]
[2.91666667 2.91666667]
[1.70782513 1.70782513]


In [14]:
a=[100,200,300,400,500]
b=[10,20,30,40,50]
Price=np.array(a)
Quantity=np.array(b)
print(np.cumprod([Price,Quantity],axis=0))

[[  100   200   300   400   500]
 [ 1000  4000  9000 16000 25000]]


# Generating Arrays

In [97]:
import numpy as  np
a=np.zeros((2,2))
print(a)

b=np.ones((2,3))
print(b)

c=np.full((2,3),5.0)
print(c)

d=np.eye((3))
print(d)

f=np.arange(20)
print(f)

e=np.linspace(1,10,5)
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5. 5. 5.]
 [5. 5. 5.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1.    3.25  5.5   7.75 10.  ]


# Sort Search and Filter

In [7]:
import numpy as np
ar=np.array([2,1,6,4])
print(np.sort(ar))


[1 2 4 6]


In [9]:
ar=np.array([2,1,6,4])
print(np.where(ar==4))
print(np.where(ar%2==0))

(array([3]),)


In [10]:
ar=np.array([1,2,3,4])  #isma array sorted hona chye 
print(np.searchsorted(ar,2))

2


In [13]:
ar=np.array([200,1,6,4])
fa=ar>35
new=ar[fa]
print(new)

ar=np.array([200,1,6,4])
fa=ar % 2 ==0
new=ar[fa]
print(new)

[200]
[200   6   4]


# Statiscal Function

In [16]:
import numpy as np
import statistics as stats
baked_food=[200,300,150,130,200,280,170,188]

a=np.array(baked_food)
print(np.mean(a))
print(np.median(a))
print(stats.mode(a))
print(np.std(a)) #kafi acha method ha agr data ka spread hanana ha , ya underroot hota ha var ka
print(np.var(a)) #square of std, agar iska var jannaa ho to underrrot std bnta 

202.25
194.0
200
55.68157235567257
3100.4375


In [19]:
tobaco=[10,35,40]
deaths=[100,200,300]
print(np.corrcoef([tobaco,deaths]))

#-1 represents inversley propotional relationship
#1 respresnts propotional relationship
#0 means no relationship

[[1.         0.93325653]
 [0.93325653 1.        ]]
