# Day 1

In [8]:
# Convert 1D array to 2D array with 2 rows

import numpy as np 
array_1d = np.array([1, 2, 3, 4, 5, 6])
array_2d = array_1d.reshape(2,-1)
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [10]:
#Multiply a 5x3 matrix by a 3x2 matrix

matrix_1 = np.random.rand(5, 3)
matrix_2 = np.random.rand(3, 2)
result = np.dot(matrix_1, matrix_2)
print(result)

[[0.76896304 1.56138915]
 [0.26836624 0.96807957]
 [0.58113332 1.31737895]
 [0.83931614 1.79963197]
 [0.30997965 0.81906244]]


In [ ]:
#Extract all odd number from array 1-20

array = np.arange(1, 21)
odd_numbers = array[array % 2 != 0]
print(odd_numbers)

In [ ]:
#Replace all odd number from array 1-10 with -1

array = np.arange(1, 11)
array[array % 2 != 0] = -1
print(array)

In [ ]:
#Convert a 1D array to a boolean array where all positive values become True

array = np.array([0, 1, -2, 3, -4, 5])
boolean_array = array > 0
print(boolean_array)

In [ ]:
#Replace all even numbers in a 1D array with their negative

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array[array % 2 == 0] = -array[array % 2 == 0]
print(array)

# Day 2

In [ ]:
#Calculate the sum of the diagonal elements of a 3x3 matrix.
n = np.arange(9).reshape(3,3)
print(n)
print(np.trace(n))


In [ ]:
#Find the indices of non-zero elements from [1,2,0,0,4,0].
n = np.array([1,2,0,0,4,0])
print(np.nonzero(n))


In [ ]:
#Reverse a 1D array (first element becomes the last).
n = np.arange(1,11)
print(np.flip(n))
#np.flip() function used to reverse the element in array
print(n[::-1]) # this is anpther way to do it


In [ ]:
#Create a 3x3 identity matrix.
n = np.eye(3,3)
print(n)


In [ ]:
#Reshape a 1D array to a 2D array with 5 rows and 2 columns.
n = np.arange(10)
n = n.reshape(5,2)
print(n)


In [ ]:
#Get the common items between two arrays.
n = np.arange(10)
n2 = np.arange(5,9)
print(np.intersect1d(n,n2))


In [ ]:
#Create a 5x5 matrix with row values ranging from 0 to 4.
n = np.zeros((5,5))
n = n+ np.arange(5)
print(n)
